# docker compose file
# build and run the container in the ../site directory
version: "3"
services:
  nginx-site:
    build:
      context: ../nginx-site
      dockerfile: Dockerfile

    # map external port 8080 to internal port 80
    ports:
      - "8080:80"

  caddy-site:
    build:
      context: ../caddy-site
      dockerfile: Dockerfile

    # map external port 8081 to internal port 80
    ports:
      - "8081:80"

  go-time:
    build:
      context: ../go-time
      dockerfile: Dockerfile

    # map external port 8082 to internal port 80
    ports:
      - "8082:80"

  deno-time:
    build:
      context: ../deno-time
      dockerfile: Dockerfile

    # map external port 8083 to internal port 8000
    ports:
      - "8083:8000"

  django-time:
    build:
      context: ../django-time
      dockerfile: Dockerfile

    # map external port 8084 to internal port 80
    ports:
      - "8084:8000"
