# docker compose file
# build and run the container in the ../site directory
version: "3"
services:
  nginx-site:
    build:
      context: ../nginx-site
      dockerfile: Dockerfile

    # map external port 8080 to internal port 80
    ports:
      - "8080:80"

  caddy-site:
    build:
      context: ../caddy-site
      dockerfile: Dockerfile

    # map external port 8081 to internal port 80
    ports:
      - "8081:80"

  go-time:
    build:
      context: ../go-time
      dockerfile: Dockerfile

    # map external port 8081 to internal port 80
    ports:
      - "8082:80"
